"""second migration

Revision ID: 4bbf39632a51
Revises: 7391c88cff7c
Create Date: 2025-12-06 13:11:28.083540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bbf39632a51'
down_revision: Union[str, Sequence[str], None] = '7391c88cff7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation_codes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('confirmation_codes', sa.Column('code', sa.String(), nullable=False))
    op.alter_column('confirmation_codes', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'confirmation_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('confirmation_codes', 'confirmation_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation_codes', sa.Column('confirmation_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'confirmation_codes', type_='foreignkey')
    op.alter_column('confirmation_codes', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('confirmation_codes', 'code')
    op.drop_column('confirmation_codes', 'user_id')
    # ### end Alembic commands ###
