"""add jwt black list 

Revision ID: efb1d80370fd
Revises: 4bbf39632a51
Create Date: 2025-12-06 14:28:17.470374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb1d80370fd'
down_revision: Union[str, Sequence[str], None] = '4bbf39632a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "JWT_blacklist",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("token", sa.String(), unique=True, nullable=False),
        sa.Column("expired_on", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("JWT_blacklist")
    # ### end Alembic commands ###
